### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by xiaoshir** [LESBAT-HEIG-VD/EcoDynElec#2]
Hi I would like to install EcoDynElec in a virtual environment but so far without success. Can anyone help please?
**I tried the [conventional install](https://ecodynelec.readthedocs.io/en/latest/#conventional-install)** on the documentation
and got the following error:

```
(myproject) C:\Users\zhang_x\Documents\Third paper>pip install elecodyn
ERROR: Could not find a version that satisfies the requirement elecodyn (from versions: none)
ERROR: No matching distribution found for elecodyn
```

**I also tried: pip install git+https://github.com/LESBAT-HEIG-VD/EcoDynElec.git**, but got the following:
```
(myproject) C:\Users\zhang_x\Documents\Third paper\EcoDynElec>pip install git+https://github.com/LESBAT-HEIG-VD/EcoDynElec.git
Collecting git+https://github.com/LESBAT-HEIG-VD/EcoDynElec.git
  Cloning https://github.com/LESBAT-HEIG-VD/EcoDynElec.git to c:\users\zhang_x\appdata\local\temp\2\pip-req-build-qd9kgqdk
  Running command git clone --filter=blob:none --quiet https://github.com/LESBAT-HEIG-VD/EcoDynElec.git 'C:\Users\zhang_x\AppData\Local\Temp\2\pip-req-build-qd9kgqdk'
  Resolved https://github.com/LESBAT-HEIG-VD/EcoDynElec.git to commit 236f26500e9eae4db920dc79476af13d0ac44c28
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\zhang_x\AppData\Local\Temp\2\pip-req-build-qd9kgqdk\setup.py", line 7, in <module>
          long_description = fh.read()
                             ^^^^^^^^^
        File "C:\Users\zhang_x\Anaconda3\envs\myproject\Lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2193: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by mijafro** [comment]
Hi, did you try with the "Getting started" instruction from the documentation : https://ecodynelec.readthedocs.io/en/latest/examples/getting_started.html ?

**Comment by fledee** [comment]
The first approach can not work: it would be needed to enter the EcoDynElec\ directory first.

It seems the `setup.py` was not very windows friendly. The issue was fixed, and the documentation was updated accordingly. I will be needed do download the package again.

Please confirm if the installation now works. If not, the solution in section [Guaranteed install](https://ecodynelec.readthedocs.io/en/latest/#guaranteed-install) would work in any case, and just requires adding a line at the start of each python script or notebook before importing `ecodynelec`.

**Comment by xiaoshir** [comment]
> Hi, did you try with the "Getting started" instruction from the documentation : https://ecodynelec.readthedocs.io/en/latest/examples/getting_started.html ?

Thanks for the reply Mija, and yes, that is where I started with.

**Comment by xiaoshir** [comment]
> The first approach can not work: it would be needed to enter the EcoDynElec\ directory first.
> 
> It seems the `setup.py` was not very windows friendly. The issue was fixed, and the documentation was updated accordingly. It will be needed do download the package again.
> 
> Please confirm if the installation now works. If not, the solution in section [Guaranteed install](https://ecodynelec.readthedocs.io/en/latest/#guaranteed-install) would work in any case, and just requires adding a line at the start of each python script or notebook before importing `ecodynelec`.

These two options did not work still:
```
(base) C:\Users\zhang_x\Documents\Third paper>git clone https://github.com/LESBAT-HEIG-VD/EcoDynElec.git
Cloning into 'EcoDynElec'...
remote: Enumerating objects: 1666, done.
remote: Counting objects: 100% (135/135), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 1666 (delta 99), reused 108 (delta 94), pack-reused 1531Receiving objects:  99% (1650/1666), 33.45 MiB | 6.68 MiB/s
Receiving objects: 100% (1666/1666), 36.12 MiB | 6.71 MiB/s, done.
Resolving deltas: 100% (1086/1086), done.

(base) C:\Users\zhang_x\Documents\Third paper>activate myproject

(myproject) C:\Users\zhang_x\Documents\Third paper>cd C:\Users\zhang_x\Documents\Third paper\EcoDynElec

(myproject) C:\Users\zhang_x\Documents\Third paper\EcoDynElec>python -m pip install ecodynelec
ERROR: Could not find a version that satisfies the requirement ecodynelec (from versions: none)
ERROR: No matching distribution found for ecodynelec

(myproject) C:\Users\zhang_x\Documents\Third paper\EcoDynElec>pip install ecodynelec
ERROR: Could not find a version that satisfies the requirement ecodynelec (from versions: none)
ERROR: No matching distribution found for ecodynelec

(myproject) C:\Users\zhang_x\Documents\Third paper\EcoDynElec>conda install elecodynelec
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - elecodynelec

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

But the following worked. Thanks. 

Would be nice for you to figure out why the above does not not work
```
(myproject) C:\Users\zhang_x\Documents\Third paper\EcoDynElec>python setup.py install
running install
C:\Users\zhang_x\Anaconda3\envs\myproject\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
C:\Users\zhang_x\Anaconda3\envs\myproject\Lib\site-packages\setuptools\_distutils\cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating ecodynelec.egg-info
writing ecodynelec.egg-info\PKG-INFO
writing dependency_links to ecodynelec.egg-info\dependency_links.txt
writing requirements to ecodynelec.egg-info\requires.txt
writing top-level names to ecodynelec.egg-info\top_level.txt
writing manifest file 'ecodynelec.egg-info\SOURCES.txt'
reading manifest file 'ecodynelec.egg-info\SOURCES.txt'
adding license file 'LICENSE.md'
writing manifest file 'ecodynelec.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
creating build
creating build\lib
creating build\lib\ecodynelec
copying ecodynelec\checking.py -> build\lib\ecodynelec
copying ecodynelec\impacts.py -> build\lib\ecodynelec
copying ecodynelec\parameter.py -> build\lib\ecodynelec
copying ecodynelec\pipelines.py -> build\lib\ecodynelec
copying ecodynelec\saving.py -> build\lib\ecodynelec
copying ecodynelec\tracking.py -> build\lib\ecodynelec
copying ecodynelec\updating.py -> build\lib\ecodynelec
copying ecodynelec\__init__.py -> build\lib\ecodynelec
creating build\lib\ecodynelec\preprocessing
copying ecodynelec\preprocessing\autocomplete.py -> build\lib\ecodynelec\preprocessing
copying ecodynelec\preprocessing\auxiliary.py -> build\lib\ecodynelec\preprocessing
copying ecodynelec\preprocessing\downloading.py -> build\lib\ecodynelec\preprocessing
copying ecodynelec\preprocessing\extracting.py -> build\lib\ecodynelec\preprocessing
copying ecodynelec\preprocessing\loading.py -> build\lib\ecodynelec\preprocessing
copying ecodynelec\preprocessing\load_impacts.py -> build\lib\ecodynelec\preprocessing
copying ecodynelec\preprocessing\residual.py -> build\lib\ecodynelec\preprocessing
copying ecodynelec\preprocessing\__init__.py -> build\lib\ecodynelec\preprocessing
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
creating build\bdist.win-amd64\egg\ecodynelec
copying build\lib\ecodynelec\checking.py -> build\bdist.win-amd64\egg\ecodynelec
copying build\lib\ecodynelec\impacts.py -> build\bdist.win-amd64\egg\ecodynelec
copying build\lib\ecodynelec\parameter.py -> build\bdist.win-amd64\egg\ecodynelec
copying build\lib\ecodynelec\pipelines.py -> build\bdist.win-amd64\egg\ecodynelec
creating build\bdist.win-amd64\egg\ecodynelec\preprocessing
copying build\lib\ecodynelec\preprocessing\autocomplete.py -> build\bdist.win-amd64\egg\ecodynelec\preprocessing
copying build\lib\ecodynelec\preprocessing\auxiliary.py -> build\bdist.win-amd64\egg\ecodynelec\preprocessing
copying build\lib\ecodynelec\preprocessing\downloading.py -> build\bdist.win-amd64\egg\ecodynelec\preprocessing
copying build\lib\ecodynelec\preprocessing\extracting.py -> build\bdist.win-amd64\egg\ecodynelec\preprocessing
copying build\lib\ecodynelec\preprocessing\loading.py -> build\bdist.win-amd64\egg\ecodynelec\preprocessing
copying build\lib\ecodynelec\preprocessing\load_impacts.py -> build\bdist.win-amd64\egg\ecodynelec\preprocessing
copying build\lib\ecodynelec\preprocessing\residual.py -> build\bdist.win-amd64\egg\ecodynelec\preprocessing
copying build\lib\ecodynelec\preprocessing\__init__.py -> build\bdist.win-amd64\egg\ecodynelec\preprocessing
copying build\lib\ecodynelec\saving.py -> build\bdist.win-amd64\egg\ecodynelec
copying build\lib\ecodynelec\tracking.py -> build\bdist.win-amd64\egg\ecodynelec
copying build\lib\ecodynelec\updating.py -> build\bdist.win-amd64\egg\ecodynelec
copying build\lib\ecodynelec\__init__.py -> build\bdist.win-amd64\egg\ecodynelec
byte-compiling build\bdist.win-amd64\egg\ecodynelec\checking.py to checking.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\ecodynelec\impacts.py to impacts.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\ecodynelec\parameter.py to parameter.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\ecodynelec\pipelines.py to pipelines.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\ecodynelec\preprocessing\autocomplete.py to autocomplete.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\ecodynelec\preprocessing\auxiliary.py to auxiliary.cpython-312.pyc
build\bdist.win-amd64\egg\ecodynelec\preprocessing\auxiliary.py:63: SyntaxWarning: invalid escape sequence '\ '
  msg = "  /!\ Some date limits are None. SwissGrid is on period {} - {}. It may not match the Generation and Exchange."
build\bdist.win-amd64\egg\ecodynelec\preprocessing\auxiliary.py:66: SyntaxWarning: invalid escape sequence '\ '
  msg = "  /!\ Resudual computed only during {} - {}. SwissGrid Data not available on the rest of the period."
byte-compiling build\bdist.win-amd64\egg\ecodynelec\preprocessing\downloading.py to downloading.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\ecodynelec\preprocessing\extracting.py to extracting.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\ecodynelec\preprocessing\loading.py to loading.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\ecodynelec\preprocessing\load_impacts.py to load_impacts.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\ecodynelec\preprocessing\residual.py to residual.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\ecodynelec\preprocessing\__init__.py to __init__.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\ecodynelec\saving.py to saving.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\ecodynelec\tracking.py to tracking.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\ecodynelec\updating.py to updating.cpython-312.pyc
byte-compiling build\bdist.win-amd64\egg\ecodynelec\__init__.py to __init__.cpython-312.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying ecodynelec.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying ecodynelec.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying ecodynelec.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying ecodynelec.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying ecodynelec.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
zip_safe flag not set; analyzing archive contents...
ecodynelec.__pycache__.updating.cpython-312: module references __file__
ecodynelec.preprocessing.__pycache__.auxiliary.cpython-312: module references __file__
creating dist
creating 'dist\ecodynelec-0.1.1-py3.12.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing ecodynelec-0.1.1-py3.12.egg
creating c:\users\zhang_x\anaconda3\envs\myproject\lib\site-packages\ecodynelec-0.1.1-py3.12.egg
Extracting ecodynelec-0.1.1-py3.12.egg to c:\users\zhang_x\anaconda3\envs\myproject\lib\site-packages
c:\users\zhang_x\anaconda3\envs\myproject\lib\site-packages\ecodynelec-0.1.1-py3.12.egg\ecodynelec\preprocessing\auxiliary.py:63: SyntaxWarning: invalid escape sequence '\ '
  msg = "  /!\ Some date limits are None. SwissGrid is on period {} - {}. It may not match the Generation and Exchange."
c:\users\zhang_x\anaconda3\envs\myproject\lib\site-packages\ecodynelec-0.1.1-py3.12.egg\ecodynelec\preprocessing\auxiliary.py:66: SyntaxWarning: invalid escape sequence '\ '
  msg = "  /!\ Resudual computed only during {} - {}. SwissGrid Data not available on the rest of the period."
Adding ecodynelec 0.1.1 to easy-install.pth file

Installed c:\users\zhang_x\anaconda3\envs\myproject\lib\site-packages\ecodynelec-0.1.1-py3.12.egg
Processing dependencies for ecodynelec==0.1.1
Searching for fonttools>=4.22.0
Reading https://pypi.org/simple/fonttools/
Downloading https://files.pythonhosted.org/packages/6f/06/c9f12f6589bba880d03c35696a3a21d8560001d7f0bff936710fa4f48c8b/fonttools-4.49.0-py3-none-any.whl#sha256=af281525e5dd7fa0b39fb1667b8d5ca0e2a9079967e14c4bfe90fd1cd13e0f18
Best match: fonttools 4.49.0
Processing fonttools-4.49.0-py3-none-any.whl
Installing fonttools-4.49.0-py3-none-any.whl to c:\users\zhang_x\anaconda3\envs\myproject\lib\site-packages
Adding fonttools 4.49.0 to easy-install.pth file
detected new path './ecodynelec-0.1.1-py3.12.egg'
Installing fonttools-script.py script to C:\Users\zhang_x\Anaconda3\envs\myproject\Scripts
Installing fonttools.exe script to C:\Users\zhang_x\Anaconda3\envs\myproject\Scripts
error: [WinError 5] Access is denied: 'C:\\Users\\zhang_x\\Anaconda3\\envs\\myproject\\Scripts\\fonttools.exe'
```

**Comment by fledee** [comment]
Command line `python -m pip install ecodynelec` (using `python` and `pip` from your virtual env), command line `pip install ecodynelec` (using `pip` from computer/anaconda) and `conda install ecodynelec` (using `conda` from computer/anaconda) will not work:

First, it tries to find the local file `./ecodynelec/setup.py` (case sensitive) from where the command is launched. But that file does not exist.
Then (in shorts), if that fails, it tries to reach online repositories to see if some package fits under the name "ecodynelec". And it does not, because the package was not integrated to any of these repositories.

The solution is, as briefly exposed in the recently corrected doc, 
- either move to `EcoDynElec\` with `cd`, then launch `python -m pip install ./`, so that `pip` can find the setup file under `./setup.py`
- or remain where the `git clone` was executed, then launch `python -m pip install EcoDynElec\` to find the file under `./EcoDynElec/setup.py`
- or use python to directly execute the file `setup.py` with `python setup.py install`, which is what worked here.

The most recent fix makes the install process independent from the OS.

It seems the issue was solved, so I close it.
